name: Magisk Build

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "native/**"
      - "build.py"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Magisk artifacts
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          is-asset-build: true

      - name: Build release
        run: ./build.py -vr -c .github/ci.prop all

      - name: Stop gradle daemon
        run: ./app/gradlew --stop

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: magisk-${{ github.sha }}
          path: out
          compression-level: 9
